### ISSUE TITLE
AuthGuards Implementation

### ISSUE THREAD

**Issue by beasli** [beasli/savya#22]
Apply guard  on all routes for logged in user
- [x] My Profile :   /account-details
- [x] My Address :  /account-addresses
- [x] My Wishlist :   /account-wishlist
- [x] My Order History : /account-history
- [x] Change Profile : /changeProfile
- [x] Checkout : /checkout

**Comment by beasli** [comment]
Checkout : /checkout
if user not added anything to cart so user should not allow to redirect this page

**Comment by Piyush287649** [comment]
checkout guard work done
