### ISSUE TITLE
Update Local storage of user info after profile update

### ISSUE THREAD

**Issue by beasli** [beasli/savya#24]
- [x] view profile api

- [x] flow of profile page

**Comment by beasli** [comment]
![screencapture-localhost-4200-changeProfile-2020-03-23-23_28_09](https://user-images.githubusercontent.com/38140579/77347733-4cbc8c80-6d5e-11ea-95ad-523da411d5b2.png)


can't update profile

**Comment by Piyush287649** [comment]
The update API gives an error i.e. "Image is required" that we don't gave at the time of registering
