### ISSUE TITLE
Add validation to register and kyc form

### ISSUE THREAD

**Issue by Piyush287649** [beasli/savya#29]
Register Form
- [x] Gst no.
- [x] Pan no.
- [x] Mobile no.
- [x] Pin code
- [x] Confirm password
- [x] Email
Kyc Form
- [x] Gst no.
- [x] Pan no.
- [x] Aadhar no.

**Comment by beasli** [comment]
NO validation is correct

**Comment by Piyush287649** [comment]
Although i have improve the validations but the aadhar card ,pan card, gst validation may be wrong .
