### ISSUE TITLE
Cart Add Api

### ISSUE THREAD

**Issue by Piyush287649** [beasli/savya#45]
Required:
{"data":[{"assests":[{"makingCharge":"10.0","materialType":"18K","metal":"Gold","option":"percentage","productId":"6","weight":"7.15"}],"category":"1","count":1,"defaultColor":"","description":"<p>Italian Jewellery</p>","productCode":"SJILR30","productId":6,"productName":"Italian Ladies Ring","productType":"ring","subCategory":"2","subSubCategory":"1","userid":"2"}]}

Response of product detail contain both gold and diamond so which should be sent in metal

**Comment by beasli** [comment]
@Piyush287649 what we have to done with this issue?
